server:
  error:
    include-stacktrace: on_param
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskManagement?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:19112006}

  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET:secret}