version: '4.1'
services:
  db:
    image: mysql
    container_name: taskManagementSpring
    environment:
      - MYSQL_ROOT_PASSWORD
      - DB_USERNAME
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - task_data:/var/lib/mysql
volumes:
  task_data: